services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://postgres:Dem4ngsar!@db:5432/mydb
    ports:
      - "5000:5000"
    depends_on:
      - db

  adminpanel:
    build:
      context: ./adminpanel
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: