services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Dem4ngsar!
      POSTGRES_DB: db_novamos
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - novamos_network

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres://developer:Dem4ngsar!@db:5432/db_novamos
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - novamos_network
    volumes:
      - ./backend/uploads/items:/app/src/api/items/uploads
      - ./backend/uploads/article:/app/src/api/article/uploads
      - ./backend/uploads/voucher:/app/src/api/voucher/uploads
      - ./backend/uploads/order:/app/src/api/order/uploads

  adminpanel:
    build:
      context: ./adminpanel
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - novamos_network

  nginx:
    image: nginx:alpine
    volumes:
      # - ./nginx-withoutssl.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount Let's Encrypt certificates
    ports:
      - "80:80"   # HTTP
      - "443:443"  # HTTPS
    depends_on:
      - adminpanel
      - backend
    networks:
      - novamos_network

volumes:
  pgdata:

networks:
  novamos_network: